language: r
cache: packages
warnings_are_errors: true

r_packages:
  - devtools
  - covr
  - magrittr
  - Rcpp
  - RcppArmadillo
  - httr
  - rmarkdown
  - testthat
  - R.rsp

## test different platforms
jobs:
  include:
  - os: linux
    r: oldrel
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y ghostscript
    env: CACHE_NAME=JOB1
  - os: linux
    r: release
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y ghostscript
    env: CACHE_NAME=JOB2
  - os: linux
    r: devel
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y ghostscript
    env: CACHE_NAME=JOB3
  - os: osx
    r: release
    osx_image: xcode11.4
    before_install:
      - |
        ## Test whether gcc is already installed
        if ! brew ls --versions gcc > /dev/null; then
            sudo rm '/usr/local/bin/gfortran'
            brew install gcc
        fi
      - brew install libssh2
      - brew install libgit2
    env: CACHE_NAME=JOB4

##create notifications
notifications:
  email:
    recipients:
      - sk@r-luminescence.de
    on_success: change
    on_failure: change

##grep data from testthat
after_success:
- Rscript -e 'covr::codecov()'
