#!/bin/bash
#
# =================================================================================================
# RLumCarlo.CHECK_AND_BUILD shell script
# author: RLumCarlo ... Sebastian Kreutzer
# previous version from Sebastian kreutzer
# date: 2017-04-01
#
# Customized R check and build routine for the R package 'RLumCarlo'
# =================================================================================================
#
#
# CONFIG AND DEFINITIONS
# =================================================================================================
#
echo "[START]"
export TERM=xterm
PATHPACKAGE=$(dirname $0)
#
check_status(){
  if [ $? == 0 ]; then
    echo "[OK]"
  else
    echo "[FAILED]"
  fi
}
#
#
# REMOVING UNWANTED FILES
# =================================================================================================
echo ""
echo "[PREPARE FOR PACKAGE CHECK]"
echo ""
#

  echo -ne "-> Clean RLumCarlo.BuildResults folder ... \t"
  find ${PATHPACKAGE}/RLumCarlo.BuildResults -type f -exec rm {} \;
  check_status

  echo -ne "-> Remove .DS_Store ... \t\t\t"
  find ${PATHPACKAGE} -name ".DS_Store" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove .Rhistory ... \t\t\t"
  find ${PATHPACKAGE} -name ".Rhistory" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove .RData ... \t\t\t\t"
  find ${PATHPACKAGE} -name ".RData" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove .RcppExports.cpp ... \t\t\t"
  find ${PATHPACKAGE}/src -name "RcppExports.cpp" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove NAMESPACE ... \t\t\t"
  find ${PATHPACKAGE} -name "NAMESPACE" -depth -exec rm {} \;
  check_status


# Rcpp
# =================================================================================================
  echo -ne "-> Build Rcpp ... \t\t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLumCarlo.BuildScripts/RLumCarlo.PBS_Rcpp.R /dev/null
  check_status


# roxygen2
# =================================================================================================
  echo -ne "-> Create empty NAMESPACE file... \t\t"
  echo '# Generated by roxygen2 (6.0.0): do not edit by hand' > NAMESPACE
  check_status

  echo -ne "-> Build documentation ... \t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLumCarlo.BuildScripts/RLumCarlo.PBS_roxygen2.R /dev/null
  check_status


#
# COMPILE FUNCTION PARAMTER LIST
# =================================================================================================

  echo -ne "-> Compile function argument list ...\t\t"
  eval R CMD BATCH ${PATHPACKAGE}/RLumCarlo.BuildScripts/RLumCarlo.PBS_Function_Arguments.R /dev/null
  check_status


# Set entry points
# =================================================================================================
  echo -ne "-> Set entry points ... \t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLumCarlo.BuildScripts/RLumCarlo.PBS_EntryPointRegistration.R /dev/null
  check_status

#
# NEWS
# =================================================================================================

  echo -ne "-> Build ASCII NEWS ... \t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLumCarlo.BuildScripts/RLumCarlo.PBS_NEWS.R /dev/null
  check_status

#
# BUILD PACKAGE
# =================================================================================================
echo ""
echo "[BUILD PACKAGE]"
echo ""

  eval R CMD build ${PATHPACKAGE}

#
# CHECK PACKAGE
# =================================================================================================
echo ""
echo "[CHECK PACKAGE]"
echo ""

  eval R CMD check --timings --as-cran ${PATHPACKAGE}/RLumCarlo*.tar.gz

  echo -ne 'Example timing warnings...:\n\n'
  eval R CMD BATCH ${PATHPACKAGE}/RLumCarlo.BuildScripts/RLumCarlo.PBS_Timings.R /dev/null
  cat ${PATHPACKAGE}/RLumCarlo.BuildResults/RLumCarlo-Ex.timings.*.WARNING


#
# INSTALL PACKAGE
# =================================================================================================
echo ""
echo "[INSTALL PACKAGE]"
echo ""

  eval R CMD INSTALL --build ${PATHPACKAGE}/RLumCarlo*.tar.gz

#
# COPY FILES AND CLEANING UP
# =================================================================================================
echo ""
echo "[OUTRO]"
echo ""

  echo -ne "-> Write BibTeX ... \t\t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLumCarlo.BuildScripts/RLumCarlo.PBS_BibTeX.R /dev/null
  check_status

  echo -ne "-> Build function list ... \t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLumCarlo.BuildScripts/RLumCarlo.PBS_Function_List.R /dev/null
  check_status

  echo -ne "-> Moving packge source files (*.tar.gz) ... \t"
  mv RLumCarlo_*.tar.gz RLumCarlo.BuildResults/ &>/dev/null
  check_status

  # only for MAC OS
  echo -ne "-> Moving packge compiles package (*.tgz) ... \t"
  mv RLumCarlo_*.tgz RLumCarlo.BuildResults/ &>/dev/null
  check_status

  echo -ne "-> Copy manual ... \t\t\t\t"
  cp RLumCarlo.Rcheck/RLumCarlo-manual.pdf RLumCarlo.BuildResults/RLumCarlo-manual.pdf &>/dev/null
  check_status

  echo -ne "-> Copy check results ... \t\t\t"
  cp RLumCarlo.Rcheck/RLumCarlo-Ex.pdf RLumCarlo.BuildResults/RLumCarlo-Ex.pdf &>/dev/null
  check_status

  echo -ne "-> Remove RLumCarlo.Rcheck ... \t\t\t"
  rm -r ${PATHPACKAGE}/RLumCarlo.Rcheck &>/dev/null
  check_status

  echo ""
  echo "[FINE]"

